checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=/home/scrutinizer/build/clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
