checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php:
            version: 7.2
            ini:
                'date.timezone': 'Asia/Shanghai'
    dependencies:
        before:
            - pecl install swoole-4.4.5
            - composer install
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis