language: php

php:
  - 7.1
  - 7.2

before_script:
  - pecl install SeasLog
  - pecl install swoole
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

matrix:
  fast_finish: true

